apiVersion: v1
kind: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 5
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp-container
          image: maha4iac/mahalogin:1
          ports:
            - containerPort: 8080
