apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 2
  selector:
    app: myapp
    version: 2.6.1
  template:
    metadata:   
      labels:
        app: myapp
        version: 2.6.1
    spec:
      containers:
        - name: myapp-container
          image: maha4iac/mahalogin:1
          ports:
            - containerPort: 8080
