apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
spec:
  replicas: 2
  selector:
    app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myappclear
    spec:
      containers:
        - name: myapp-container
          image: maha4iac/mahalogin:1
          ports:
            - containerPort: 8080
